name: Check Pull Request

on: pull_request

permissions:
  contents: read

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WPCS check
          uses: 10up/wpcs-action@stable
        - name: Dependency Review
          uses: actions/dependency-review-action@v3
          with:
            license-check: true
            vulnerability-check: false
            config-file: ./.github/dependency-review-config.yml